debug: True
secret_key: "tt52p2jsQTywaz1nWfPzQmkC3n1cM0q5"
installed_apps:
  - django.contrib.contenttypes
  - tardis
rabbitmq:
  host: rabbitmq
  port: "5672"
  user: user
  password: password
  vhost: /
celery:
  result_backend: rpc
  acks_late: True
  default_queue: verify
  max_task_priority: 10
  default_task_priority: 5
api:
  queue: celery
  task_priority: 5
